### ISSUE TITLE
Null pointers when trying to run the test class

### ISSUE THREAD

**Issue by jefflynn343** [harm27/obs-java-client#82]
The constructor for OBSWebSocket wants to first make an authentication handler which relies on the requestSenderManager, but the requestSenderManager is null because it gets set further down in the constructor . I'm not sure if Im missing something here...

I flipped some code around to first make the request sender manager, took out the part of the RequestSenderManager that relies on the authenticate. Then I created my authentication handler, and then called my new method to add the part of the RequestSender that I took out to bypass the null. 

Thanks!

**Comment by harm27** [comment]
Thanks, i also found the issue myself when testing the changes to fully support the batching.
So i will fix it next couple of weeks, since some other elements after it also broke.

**Comment by harm27** [comment]
Correct, as far as i can see now. 
Will look if i have time next couple of days to get the issues fixed.
If you find more detail in the OBS Websocket debug logging or some other way, i will try to fix it.
Bu otherwise i will look into it myself if i can find the issue.

**Comment by jefflynn343** [comment]
Debugging shows this when I try to issue the command:

{"requestType":"nl.harm27.obs.websocket.api.requests.recording.PauseRecording$Response","messageId":"4"}'
17:37:19.837: [obs-websocket] Response << '{
17:37:19.837:     "error": "missing request parameters",
17:37:19.837:     "status": "error"
17:37:19.837: }

This is what I am sending:
{"requestType":"nl.harm27.obs.websocket.api.requests.recording.PauseRecording$Response","messageId":"4"}

I did not include the "builder" field from the BaseRequest. I wonder if thats the issue.

**Comment by harm27** [comment]
One issue i see is that it is sending the class name as requestType. 
OBS WebSocket is expecting there only the requestType, in this case, PauseRecording.

**Comment by jefflynn343** [comment]
Ah, let me see if that fixes it. It is expecting those two parameters though? 

{
"messageId" : "someNumber",
"requestType" : "PauseRecording"
}

Wondering if I may be missing a field

**Comment by jefflynn343** [comment]
Looks like the same issue here:

[obs-websocket] Request >> '{"requestType":"PauseRecording","messageId":"3"}'
17:52:41.364: [obs-websocket] Response << '{
17:52:41.364:     "error": "missing request parameters",
17:52:41.364:     "status": "error"
17:52:41.364: }'

I must be missing a parameter

**Comment by harm27** [comment]
I just figured out what it probably is.
My json parser also converts the field names, since the api names are formatted in a format that isn't valid in Java. 
RequestType and MessageId become request-type and message-id.

**Comment by harm27** [comment]
It is one of the issues that is gonna get fixed by OBS WebSocket 5.0 that is currently in development. 
As soon as that gets a bit more fleshed out i will need to work out how to change this client library to properly work with the new major version that is upcoming.

**Comment by jefflynn343** [comment]
I turned off authentication and got it working
